// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ReadingWebsite.Models;

public partial class dbYuantaProjectContext : DbContext
{
    public dbYuantaProjectContext(DbContextOptions<dbYuantaProjectContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TArticle> TArticles { get; set; }

    public virtual DbSet<TLog> TLogs { get; set; }

    public virtual DbSet<TUser> TUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TArticle>(entity =>
        {
            entity.HasKey(e => e.FDocumentId);

            entity.ToTable("tArticle");

            entity.Property(e => e.FDocumentId).HasColumnName("fDocumentId");
            entity.Property(e => e.FContent).HasColumnName("fContent");
            entity.Property(e => e.FTitle)
                .HasMaxLength(50)
                .HasColumnName("fTitle");
        });

        modelBuilder.Entity<TLog>(entity =>
        {
            entity.HasKey(e => e.FLogId);

            entity.ToTable("tLog");

            entity.Property(e => e.FLogId).HasColumnName("fLogId");
            entity.Property(e => e.FClientIp)
                .HasMaxLength(50)
                .HasColumnName("fClientIP");
            entity.Property(e => e.FDocumentId).HasColumnName("fDocumentId");
            entity.Property(e => e.FEndTime)
                .HasColumnType("datetime")
                .HasColumnName("fEndTime");
            entity.Property(e => e.FStartTime)
                .HasColumnType("datetime")
                .HasColumnName("fStartTime");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FDocument).WithMany(p => p.TLogs)
                .HasForeignKey(d => d.FDocumentId)
                .HasConstraintName("FK_tLog_tArticle");

            entity.HasOne(d => d.FUser).WithMany(p => p.TLogs)
                .HasForeignKey(d => d.FUserId)
                .HasConstraintName("FK_tLog_tUser");
        });

        modelBuilder.Entity<TUser>(entity =>
        {
            entity.HasKey(e => e.FUserId);

            entity.ToTable("tUser");

            entity.Property(e => e.FUserId).HasColumnName("fUserId");
            entity.Property(e => e.FAccount)
                .HasMaxLength(50)
                .HasColumnName("fAccount");
            entity.Property(e => e.FPassword)
                .HasMaxLength(50)
                .HasColumnName("fPassword");
            entity.Property(e => e.FUserName)
                .HasMaxLength(50)
                .HasColumnName("fUserName");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}