// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadingWebsite.Models;

public partial class TArticle
{
    public int FDocumentId { get; set; }

    public string FTitle { get; set; }

    public string FContent { get; set; }

    public virtual ICollection<TLog> TLogs { get; set; } = new List<TLog>();
}