// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ReadingService.Models;

public partial class TLog
{
    public int FLogId { get; set; }

    public int? FUserId { get; set; }

    public int? FDocumentId { get; set; }

    public DateTime? FStartTime { get; set; }

    public DateTime? FEndTime { get; set; }

    public string FClientIp { get; set; }

    public virtual TArticle FDocument { get; set; }

    public virtual TUser FUser { get; set; }
}